name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check codestyle
      run: git ls-files *.cpp | xargs clang-format -i --verbose && git diff --exit-code
      
    - name: Build
      run: make
       
    - name: test
      run: make test
      
    - name: Run test
      run: ./bin/test
